<Project>
    <PropertyGroup>
        <DefineConstants>
            $(DefineConstants); 
            NK_RENDERING_PROFILING; 
            PolyPublic
        </DefineConstants>

        <PolyArgumentExceptions>true</PolyArgumentExceptions>
        
        <DefineConstants>$(DefineConstants.Replace('%0A', '').Replace('%0D', '').Replace(' ', ''))</DefineConstants>
        
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <NoWarn>$(NoWarn)</NoWarn>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>obj\Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
</Project>