<Project>
    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <DefineConstants>
            $(DefineConstants); 
            NK_RENDERING_PROFILING
        </DefineConstants>

        <PolyArgumentExceptions>true</PolyArgumentExceptions>
        <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
        
        <DefineConstants>$(DefineConstants.Replace('%0A', '').Replace('%0D', '').Replace(' ', ''))</DefineConstants>
        
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <NoWarn>$(NoWarn)</NoWarn>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>obj\Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
    
<!--    <ItemGroup>-->
<!--        <PackageReference Include="Polyfill" Version="11.4.1">-->
<!--            <PrivateAssets>all</PrivateAssets>-->
<!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--        </PackageReference>-->
<!--    </ItemGroup>-->
</Project>