//
// NeoKolors
// Copyright (c) 2026 KryKom
//

using HasFlagExtension;
using NeoKolors.Console.Driver.Windows;

namespace NeoKolors.Console;

/// <summary>
/// Represents key codes for input devices, such as keyboards and mice.
///
/// <b>NOTE</b>: The values of the keys in this enum are the same as the keys' values
/// in <see cref="WinImports.WinVirtualKeyCode"/>.
/// </summary>
/// <remarks>
/// This enumeration provides a comprehensive set of constants for identifying keyboard keys, mouse buttons,
/// and other input-related actions. It includes standard alphanumeric keys, function keys, control keys,
/// and specialized keys, as well as mouse buttons and multimedia keys.
/// Flags are grouped using custom attributes such as [FlagGroup("Alt")], [FlagGroup("Shift")],
/// [FlagGroup("Control")], and [FlagGroup("Win")].
/// </remarks>
[FlagGroup("Alt", "Is")]
[FlagGroup("Shift", "Is")]
[FlagGroup("Control", "Is")]
[FlagGroup("Win", "Is")]
[FlagGroup("Arrow", "Is")]
[FlagGroup("Mouse", "Is")]
[FlagGroup("Function", "Is")]
public enum KeyCode {
    
    NONE = 0,
    
    [FlagGroup("Mouse")] LEFT_MOUSE_BUTTON = 0x01,
    [FlagGroup("Mouse")] RIGHT_MOUSE_BUTTON = 0x02,
    [FlagGroup("Mouse")] MIDDLE_MOUSE_BUTTON = 0x04,
    [FlagGroup("Mouse")] X1_MOUSE_BUTTON = 0x05,
    [FlagGroup("Mouse")] X2_MOUSE_BUTTON = 0x06,
    
    CANCEL = 0x03,
    BACKSPACE = 0x08,
    TAB = 0x09,
    CLEAR = 0x0C,
    RETURN = 0x0D,
    ENTER = 0x0D,
    PAUSE = 0x13,
    CAPS_LOCK = 0x14,
    
    IME_KANA = 0x15,
    IME_HANGUL = 0x15,
    IME_ON = 0x16,
    IME_JUNJA = 0x17,
    IME_FINAL = 0x18,
    IME_HANJA = 0x19,
    IME_KANJI = 0x19,
    IME_OFF = 0x1A,
    IME_CONVERT = 0x1C,
    IME_NONCONVERT = 0x1D,
    IME_ACCEPT = 0x1E,
    IME_MODECHANGE = 0x1F,
    
    ESCAPE = 0x1B,
    SPACE = 0x20,
    PAGE_UP = 0x21,
    PAGE_DOWN = 0x22,
    END = 0x23,
    HOME = 0x24,
    
    [FlagGroup("Win")]     LEFT_WIN      = 0x5B,
    [FlagGroup("Win")]     RIGHT_WIN     = 0x5C,
    [FlagGroup("Shift")]   SHIFT         = 0x10,
    [FlagGroup("Shift")]   LEFT_SHIFT    = 0xA0,
    [FlagGroup("Shift")]   RIGHT_SHIFT   = 0xA1,
    [FlagGroup("Control")] CONTROL       = 0x11,
    [FlagGroup("Control")] LEFT_CONTROL  = 0xA2,
    [FlagGroup("Control")] RIGHT_CONTROL = 0xA3,
    [FlagGroup("Alt")]     ALT           = 0x12,
    [FlagGroup("Alt")]     LEFT_MENU     = 0xA4,
    [FlagGroup("Alt")]     RIGHT_MENU    = 0xA5,
    
    [FlagGroup("Arrow")] ARROW_LEFT  = 0x25,
    [FlagGroup("Arrow")] ARROW_UP    = 0x26,
    [FlagGroup("Arrow")] ARROW_RIGHT = 0x27,
    [FlagGroup("Arrow")] ARROW_DOWN  = 0x28,
    
    SELECT = 0x29,
    PRINT = 0x2A,
    EXECUTE = 0x2B,
    SNAPSHOT = 0x2C,
    INSERT = 0x2D,
    DELETE = 0x2E,
    HELP = 0x2F,
    
    D0 = 0x30,
    D1 = 0x31,
    D2 = 0x32,
    D3 = 0x33,
    D4 = 0x34,
    D5 = 0x35,
    D6 = 0x36,
    D7 = 0x37,
    D8 = 0x38,
    D9 = 0x39,
    
    A = 0x41,
    B = 0x42,
    C = 0x43,
    D = 0x44,
    E = 0x45,
    F = 0x46,
    G = 0x47,
    H = 0x48,
    I = 0x49,
    J = 0x4A,
    K = 0x4B,
    L = 0x4C,
    M = 0x4D,
    N = 0x4E,
    O = 0x4F,
    P = 0x50,
    Q = 0x51,
    R = 0x52,
    S = 0x53,
    T = 0x54,
    U = 0x55,
    V = 0x56,
    W = 0x57,
    X = 0x58,
    Y = 0x59,
    Z = 0x5A,
    
    APPS = 0x5D,
    SLEEP = 0x5F,
    
    NUMPAD0 = 0x60,
    NUMPAD1 = 0x61,
    NUMPAD2 = 0x62,
    NUMPAD3 = 0x63,
    NUMPAD4 = 0x64,
    NUMPAD5 = 0x65,
    NUMPAD6 = 0x66,
    NUMPAD7 = 0x67,
    NUMPAD8 = 0x68,
    NUMPAD9 = 0x69,
    MULTIPLY = 0x6A,
    ADD = 0x6B,
    SEPARATOR = 0x6C,
    SUBTRACT = 0x6D,
    DECIMAL = 0x6E,
    DIVIDE = 0x6F,
    
    [FlagGroup("Function")] F1  = 0x70,
    [FlagGroup("Function")] F2  = 0x71,
    [FlagGroup("Function")] F3  = 0x72,
    [FlagGroup("Function")] F4  = 0x73,
    [FlagGroup("Function")] F5  = 0x74,
    [FlagGroup("Function")] F6  = 0x75,
    [FlagGroup("Function")] F7  = 0x76,
    [FlagGroup("Function")] F8  = 0x77,
    [FlagGroup("Function")] F9  = 0x78,
    [FlagGroup("Function")] F10 = 0x79,
    [FlagGroup("Function")] F11 = 0x7A,
    [FlagGroup("Function")] F12 = 0x7B,
    [FlagGroup("Function")] F13 = 0x7C,
    [FlagGroup("Function")] F14 = 0x7D,
    [FlagGroup("Function")] F15 = 0x7E,
    [FlagGroup("Function")] F16 = 0x7F,
    [FlagGroup("Function")] F17 = 0x80,
    [FlagGroup("Function")] F18 = 0x81,
    [FlagGroup("Function")] F19 = 0x82,
    [FlagGroup("Function")] F20 = 0x83,
    [FlagGroup("Function")] F21 = 0x84,
    [FlagGroup("Function")] F22 = 0x85,
    [FlagGroup("Function")] F23 = 0x86,
    [FlagGroup("Function")] F24 = 0x87,
    
    NUMLOCK = 0x90,
    SCROLL = 0x91,
    
    BROWSER_BACK = 0xA6,
    BROWSER_FORWARD = 0xA7,
    BROWSER_REFRESH = 0xA8,
    BROWSER_STOP = 0xA9,
    BROWSER_SEARCH = 0xAA,
    BROWSER_FAVORITES = 0xAB,
    BROWSER_HOME = 0xAC,
    
    VOLUME_MUTE = 0xAD,
    VOLUME_DOWN = 0xAE,
    VOLUME_UP = 0xAF,
    
    MEDIA_NEXT_TRACK = 0xB0,
    MEDIA_PREV_TRACK = 0xB1,
    MEDIA_STOP = 0xB2,
    MEDIA_PLAY_PAUSE = 0xB3,
    
    LAUNCH_MAIL = 0xB4,
    LAUNCH_MEDIA_SELECT = 0xB5,
    LAUNCH_APP1 = 0xB6,
    LAUNCH_APP2 = 0xB7,
    
    GAMEPAD_A = 0xC3,
    GAMEPAD_B = 0xC4,
    GAMEPAD_X = 0xC5,
    GAMEPAD_Y = 0xC6,
    GAMEPAD_RIGHT_SHOULDER = 0xC7,
    GAMEPAD_LEFT_SHOULDER = 0xC8,
    GAMEPAD_RIGHT_TRIGGER = 0xC9,
    GAMEPAD_LEFT_TRIGGER = 0xDA,
    GAMEPAD_DPAD_UP = 0xCB,
    GAMEPAD_DPAD_DOWN = 0xCC,
    GAMEPAD_DPAD_LEFT = 0xCD,
    GAMEPAD_DPAD_RIGHT = 0xCE,
    GAMEPAD_MENU = 0xCF,
    GAMEPAD_VIEW = 0xD0,
    GAMEPAD_LEFT_THUMBSTICK_BUTTON = 0xD1,
    GAMEPAD_RIGHT_THUMBSTICK_BUTTON = 0xD2,
    GAMEPAD_LEFT_THUMBSTICK_UP = 0xD3,
    GAMEPAD_LEFT_THUMBSTICK_DOWN = 0xD4,
    GAMEPAD_LEFT_THUMBSTICK_RIGHT = 0xD5,
    GAMEPAD_LEFT_THUMBSTICK_LEFT = 0xD6,
    GAMEPAD_RIGHT_THUMBSTICK_UP = 0xD7,
    GAMEPAD_RIGHT_THUMBSTICK_DOWN = 0xD8,
    GAMEPAD_RIGHT_THUMBSTICK_RIGHT = 0xD9,
    GAMEPAD_RIGHT_THUMBSTICK_LEFT = 0xDA,
    
    OEM_1 = 0xBA,
    OEM_PLUS = 0xBB,
    OEM_COMMA = 0xBC,
    OEM_MINUS = 0xBD,
    OEM_PERIOD = 0xBE,
    OEM_2 = 0xBF,
    OEM_3 = 0xC0,
    OEM_4 = 0xDB,
    OEM_5 = 0xDC,
    OEM_6 = 0xDD,
    OEM_7 = 0xDE,
    OEM_8 = 0xDF,
    OEM_102 = 0xE2,
    PROCESSKEY = 0xE5,
    PACKET = 0xE7,
    ATTN = 0xF6,
    CRSEL = 0xF7,
    EXSEL = 0xF8,
    EREOF = 0xF9,
    PLAY = 0xFA,
    ZOOM = 0xFB,
    NONAME = 0xFC,
    PA1 = 0xFD,
    OEM_CLEAR = 0xFE,
}