// NeoKolors
// Copyright (c) 2025 KryKom

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// ReSharper disable ArrangeAccessorOwnerBody
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

namespace NeoKolors.Tui.Fonts.V2.Serialization.Xml;

/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
[XmlRoot("Font", Namespace = NKFontSchema.SCHEMA_NAMESPACE, IsNullable=false)]
public class FontConfig {
        
    private Name _nameField;
        
    private Monospace _monospaceField;
        
    private LetterWidth _letterWidthField;
        
    private LetterHeight _letterHeightField;
        
    private Ligatures _ligaturesField;
        
    private Kerning _kerningField;
        
    private CharSpacing _charSpacingField;
        
    private LineSpacing _lineSpacingField;
    
    private WordSpacing _wordSpacingField;
        
    private Global _globalField;
        
    /// <remarks/>
    public Name Name {
        get {
            return _nameField;
        }
        set {
            _nameField = value;
        }
    }
        
    /// <remarks/>
    public Monospace Monospace {
        get {
            return _monospaceField;
        }
        set {
            _monospaceField = value;
        }
    }
        
    /// <remarks/>
    public LetterWidth LetterWidth {
        get {
            return _letterWidthField;
        }
        set {
            _letterWidthField = value;
        }
    }
        
    /// <remarks/>
    public LetterHeight LetterHeight {
        get {
            return _letterHeightField;
        }
        set {
            _letterHeightField = value;
        }
    }
        
    /// <remarks/>
    public Ligatures Ligatures {
        get {
            return _ligaturesField;
        }
        set {
            _ligaturesField = value;
        }
    }
        
    /// <remarks/>
    public Kerning Kerning {
        get {
            return _kerningField;
        }
        set {
            _kerningField = value;
        }
    }
        
    /// <remarks/>
    public CharSpacing CharSpacing {
        get {
            return _charSpacingField;
        }
        set {
            _charSpacingField = value;
        }
    }
        
    /// <remarks/>
    public LineSpacing LineSpacing {
        get {
            return _lineSpacingField;
        }
        set {
            _lineSpacingField = value;
        }
    }

    public WordSpacing WordSpacing {
        get {
            return _wordSpacingField;
        }
        set {
            _wordSpacingField = value;
        }
    }
        
    /// <remarks/>
    public Global Global {
        get {
            return _globalField;
        }
        set {
            _globalField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class WordSpacing {
}

/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Name {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType("AutoCompound", Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public class XmlAutoCompoundGlyphInfo {
        
    private Mask _maskField;
        
    private bool _isMainField;
    
    private bool _mainFirstField;
        
    private Align _alignField;
        
    private AutoCompoundApplicable _applicableField;
        
    private string _symbolField;
        
    private string _baseIdField;
        
    private string _idField;
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    public bool IsMain {
        get {
            return _isMainField;
        }
        set {
            _isMainField = value;
        }
    }

    /// <remarks/>
    public bool MainFirst {
        get {
            return _mainFirstField;
        }
        set {
            _mainFirstField = value;
        }
    }
        
    /// <remarks/>
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    public AutoCompoundApplicable Applicable {
        get {
            return _applicableField;
        }
        set {
            _applicableField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string BaseId {
        get {
            return _baseIdField;
        }
        set {
            _baseIdField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Id {
        get {            
            return Equals(_idField, null) ? _symbolField : _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Mask {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Align {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public class AutoCompoundApplicable {
        
    private string _charsField;
        
    private AutoCompoundApplicableGroup[] _groupField;
        
    /// <remarks/>
    public string Chars {
        get {
            return _charsField;
        }
        set {
            _charsField = value;
        }
    }
        
    /// <remarks/>
    [XmlElement("Group")]
    public AutoCompoundApplicableGroup[] Group {
        get {
            return _groupField;
        }
        set {
            _groupField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
[Flags]
public enum AutoCompoundApplicableGroup {
    
    /// <remarks/>
    NONE = 0,
        
    /// <remarks/>
    [XmlEnum("vowels-upper")]
    VOWELS_UPPER = 1,
        
    /// <remarks/>
    [XmlEnum("vowels-lower")]
    VOWELS_LOWER = 2,
        
    /// <remarks/>
    [XmlEnum("vowels")]
    VOWELS = VOWELS_LOWER | VOWELS_UPPER,
    
    /// <remarks/>
    [XmlEnum("consonants-upper")]
    CONSONANTS_UPPER = 4,
        
    /// <remarks/>
    [XmlEnum("consonants-lower")]
    CONSONANTS_LOWER = 8,
        
    /// <remarks/>
    [XmlEnum("consonants")]
    CONSONANTS = CONSONANTS_UPPER | CONSONANTS_LOWER,
        
    /// <remarks/>
    [XmlEnum("letters-upper")]
    LETTERS_UPPER = CONSONANTS_UPPER | VOWELS_UPPER,
        
    /// <remarks/>
    [XmlEnum("letters-lower")]
    LETTERS_LOWER = CONSONANTS_LOWER | VOWELS_LOWER,
        
    /// <remarks/>
    [XmlEnum("letters")]
    LETTERS = CONSONANTS | VOWELS,
        
    /// <remarks/>
    [XmlEnum("numbers")]
    NUMBERS = 16,
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType("Compound", Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlCompoundGlyphInfo {
        
    private string _mainField;
        
    private string _secondaryField;
        
    private Align _alignField;
        
    private string _symbolField;
        
    private string _idField;
        
    /// <remarks/>
    public string Main {
        get {
            return _mainField;
        }
        set {
            _mainField = value;
        }
    }
        
    /// <remarks/>
    public string Secondary {
        get {
            return _secondaryField;
        }
        set {
            _secondaryField = value;
        }
    }
        
    /// <remarks/>
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Id {
        get {
            return Equals(_idField, null) ? _symbolField : _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType("Ligature", Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlLigatureGlyphInfo {
        
    private AlignPointReplace _alignPointReplaceField = AlignPointReplace.NewBckg();
        
    private Mask _maskField;
        
    private int _baselineField;
        
    private string _symbolField;
        
    private string _fileField;
        
    private string _idField;
        
    /// <remarks/>
    public AlignPointReplace AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    // [XmlElement(DataType="integer")]
    public int Baseline {
        get {
            return _baselineField;
        }
        set {
            _baselineField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string File {
        get {
            return _fileField;
        }
        set {
            _fileField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Id {
        get {
            return Equals(_idField, null) ? _symbolField : _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class AlignPointReplace {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType("Component", Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlComponentGlyphInfo {
        
    private AlignPointReplace _alignPointReplaceField = AlignPointReplace.NewBckg();
        
    private Mask _maskField;
        
    private int _baselineField;
        
    private string _symbolField;
        
    private string _fileField;
        
    private string _idField;

    private string _alignPointsField;
        
    /// <remarks/>
    public AlignPointReplace AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    // [XmlElement(DataType="integer")]
    public int Baseline {
        get {
            return _baselineField;
        }
        set {
            _baselineField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string File {
        get {
            return _fileField;
        }
        set {
            _fileField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute]
    public string Id {
        get {
            return Equals(_idField, null) ? _symbolField : _idField;
        }
        set {
            _idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute]
    public string AlignPoints {
        get {
            return _alignPointsField;
        }
        set {
            _alignPointsField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public class Global {
        
    private Align _alignField;
        
    private Mask _maskField;
        
    private AlignPointReplace _alignPointReplaceField = AlignPointReplace.NewBckg();
    
    private string _alignPointsField;
        
    /// <remarks/>
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    public AlignPointReplace AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
    
    /// <remarks/>
    public string AlignPoints {
        get {
            return _alignPointsField;
        }
        set {
            _alignPointsField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class LineSpacing {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class CharSpacing {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Kerning {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Ligatures {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class LetterHeight {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class LetterWidth {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Monospace {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
public partial class MapPath {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
[XmlRoot(Namespace = NKFontSchema.SCHEMA_NAMESPACE, IsNullable=false)]
public partial class FontMap {
        
    private object[] _itemsField;
        
    /// <remarks/>
    [XmlElement("AutoCompound", typeof(XmlAutoCompoundGlyphInfo))]
    [XmlElement("Component", typeof(XmlComponentGlyphInfo))]
    [XmlElement("Compound", typeof(XmlCompoundGlyphInfo))]
    [XmlElement("Ligature", typeof(XmlLigatureGlyphInfo))]
    public object[] Items {
        get {
            return _itemsField;
        }
        set {
            _itemsField = value;
        }
    }
}