// NeoKolors
// Copyright (c) 2025 KryKom

// This source code was auto-generated by the xsd tool, Version=4.8.3928.0.
// edited

// ReSharper disable ArrangeAccessorOwnerBody
// ReSharper disable PartialTypeWithSinglePart
#pragma warning disable CS8618

namespace NeoKolors.Tui.Fonts.Serialization.Xml;

using System.Xml.Serialization;
using System.Diagnostics;
using System.ComponentModel;
using System.CodeDom.Compiler;
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
[XmlRoot("Font", Namespace=NKFontSchema.SCHEMA_NAMESPACE, IsNullable=false)]
public partial class FontConfig {
        
    private Name _nameField;
        
    private Version _versionField;
        
    private bool _ligaturesField;
        
    private int _letterSpacingField;
        
    private int _lineSpacingField;
        
    private Global _globalField;
        
    private object _itemField;
        
    public FontConfig() {
        _ligaturesField = true;
    }
        
    /// <remarks/>
    public Name Name {
        get {
            return _nameField;
        }
        set {
            _nameField = value;
        }
    }
        
    /// <remarks/>
    public Version Version {
        get {
            return _versionField;
        }
        set {
            _versionField = value;
        }
    }
        
    /// <remarks/>
    [DefaultValue(true)]
    public bool Ligatures {
        get {
            return _ligaturesField;
        }
        set {
            _ligaturesField = value;
        }
    }
        
    /// <remarks/>
    public int LetterSpacing {
        get {
            return _letterSpacingField;
        }
        set {
            _letterSpacingField = value;
        }
    }
        
    /// <remarks/>
    public int LineSpacing {
        get {
            return _lineSpacingField;
        }
        set {
            _lineSpacingField = value;
        }
    }
        
    /// <remarks/>
    public Global Global {
        get {
            return _globalField;
        }
        set {
            _globalField = value;
        }
    }
        
    /// <remarks/>
    [XmlElement("Monospace", typeof(Monospace))]
    [XmlElement("Variable", typeof(Variable))]
    public object Item {
        get {
            return _itemField;
        }
        set {
            _itemField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Name {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType("AutoCompound", Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlAutoCompoundGlyphInfo {
        
    private Mask _maskField;
        
    private bool _isMainField;
        
    private bool _isMainFieldSpecified;
        
    private bool _mainFirstField;
        
    private bool _mainFirstFieldSpecified;
        
    private Align _alignField;
        
    private AutoCompoundApplicable _applicableField;
        
    private string _symbolField;
        
    private string _baseIdField;
        
    private string _idField;
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    public bool IsMain {
        get {
            return _isMainField;
        }
        set {
            _isMainField = value;
        }
    }
        
    /// <remarks/>
    [XmlIgnore()]
    public bool IsMainSpecified {
        get {
            return _isMainFieldSpecified;
        }
        set {
            _isMainFieldSpecified = value;
        }
    }
        
    /// <remarks/>
    public bool MainFirst {
        get {
            return _mainFirstField;
        }
        set {
            _mainFirstField = value;
        }
    }
        
    /// <remarks/>
    [XmlIgnore()]
    public bool MainFirstSpecified {
        get {
            return _mainFirstFieldSpecified;
        }
        set {
            _mainFirstFieldSpecified = value;
        }
    }
        
    /// <remarks/>
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    public AutoCompoundApplicable Applicable {
        get {
            return _applicableField;
        }
        set {
            _applicableField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string BaseId {
        get {
            return _baseIdField;
        }
        set {
            _baseIdField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Id {
        get {
            return _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Mask {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Align {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class AutoCompoundApplicable {
        
    private string _charsField;
        
    private AutoCompoundApplicableGroup[] _groupField;
        
    /// <remarks/>
    public string Chars {
        get {
            return _charsField;
        }
        set {
            _charsField = value;
        }
    }
        
    /// <remarks/>
    [XmlElement("Group")]
    public AutoCompoundApplicableGroup[] Group {
        get {
            return _groupField;
        }
        set {
            _groupField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[Flags]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public enum AutoCompoundApplicableGroup {
    
    /// <remarks/>
    [XmlEnum("none")]
    NONE = 0,
    
    /// <remarks/>
    [XmlEnum("vowels-upper")]
    VOWELS_UPPER,
        
    /// <remarks/>
    [XmlEnum("vowels-lower")]
    VOWELS_LOWER,
        
    /// <remarks/>
    [XmlEnum("vowels")]
    VOWELS,
        
    /// <remarks/>
    [XmlEnum("letters-upper")]
    LETTERS_UPPER,
        
    /// <remarks/>
    [XmlEnum("letters-lower")]
    LETTERS_LOWER,
        
    /// <remarks/>
    [XmlEnum("letters")]
    LETTERS,
        
    /// <remarks/>
    [XmlEnum("consonants-upper")]
    CONSONANTS_UPPER,
        
    /// <remarks/>
    [XmlEnum("consonants-lower")]
    CONSONANTS_LOWER,
        
    /// <remarks/>
    [XmlEnum("consonants")]
    CONSONANTS,
        
    /// <remarks/>
    [XmlEnum("numbers")]
    NUMBERS,
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType("Compound", Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlCompoundGlyphInfo {
        
    private string _mainField;
        
    private string _secondaryField;
        
    private Align _alignField;
        
    private string _symbolField;
        
    private string _idField;
        
    /// <remarks/>
    public string Main {
        get {
            return _mainField;
        }
        set {
            _mainField = value;
        }
    }
        
    /// <remarks/>
    public string Secondary {
        get {
            return _secondaryField;
        }
        set {
            _secondaryField = value;
        }
    }
        
    /// <remarks/>
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Id {
        get {
            return _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType("Ligature", Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlLigatureGlyphInfo {
        
    private string _alignPointReplaceField;
        
    private Mask _maskField;
        
    private int _baselineField;
        
    private string _symbolField;
        
    private string _fileField;
        
    private string _idField;
        
    /// <remarks/>
    public string AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    public int Baseline {
        get {
            return _baselineField;
        }
        set {
            _baselineField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string File {
        get {
            return _fileField;
        }
        set {
            _fileField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Id {
        get {
            return _idField;
        }
        set {
            _idField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType("Component", Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class XmlComponentGlyphInfo {
        
    private AlignPointReplace _alignPointReplaceField;
        
    private Mask _maskField;
        
    private int _baselineField;
        
    private string _symbolField;
        
    private string _fileField;
        
    private string _idField;
        
    private string _alignPointsField;
        
    /// <remarks/>
    public AlignPointReplace AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
        
    /// <remarks/>
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    public int Baseline {
        get {
            return _baselineField;
        }
        set {
            _baselineField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Symbol {
        get {
            return _symbolField;
        }
        set {
            _symbolField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string File {
        get {
            return _fileField;
        }
        set {
            _fileField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string Id {
        get {
            return _idField;
        }
        set {
            _idField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttribute()]
    public string AlignPoints {
        get {
            return _alignPointsField;
        }
        set {
            _alignPointsField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Variable {
        
    private bool _kerningField;
        
    private bool _lineKerningField;
        
    private int _wordSpacingField;
        
    private int _emptyLineHeightField;
        
    public Variable() {
        _emptyLineHeightField = 2;
    }
        
    /// <remarks/>
    public bool Kerning {
        get {
            return _kerningField;
        }
        set {
            _kerningField = value;
        }
    }
        
    /// <remarks/>
    public bool LineKerning {
        get {
            return _lineKerningField;
        }
        set {
            _lineKerningField = value;
        }
    }
        
    /// <remarks/>
    public int WordSpacing {
        get {
            return _wordSpacingField;
        }
        set {
            _wordSpacingField = value;
        }
    }
        
    /// <remarks/>
    [DefaultValue(2)]
    public int EmptyLineHeight {
        get {
            return _emptyLineHeightField;
        }
        set {
            _emptyLineHeightField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Monospace {
        
    private ushort _letterWidthField;
        
    private ushort _letterHeightField;
        
    private bool _alignToGridField;
        
    public Monospace() {
        _alignToGridField = false;
    }
        
    /// <remarks/>
    public ushort LetterWidth {
        get {
            return _letterWidthField;
        }
        set {
            _letterWidthField = value;
        }
    }
        
    /// <remarks/>
    public ushort LetterHeight {
        get {
            return _letterHeightField;
        }
        set {
            _letterHeightField = value;
        }
    }
        
    /// <remarks/>
    [DefaultValue(false)]
    public bool AlignToGrid {
        get {
            return _alignToGridField;
        }
        set {
            _alignToGridField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Global {
        
    private Align _alignField;
        
    private Mask _maskField;
        
    private AlignPointReplace? _alignPointReplaceField;
        
    private string _alignPointsField;
        
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type Align is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='top-center' attribute.
    public Align Align {
        get {
            return _alignField;
        }
        set {
            _alignField = value;
        }
    }
        
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type Mask is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='bckg' attribute.
    public Mask Mask {
        get {
            return _maskField;
        }
        set {
            _maskField = value;
        }
    }
        
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Object is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='bckg' attribute.
    public AlignPointReplace? AlignPointReplace {
        get {
            return _alignPointReplaceField;
        }
        set {
            _alignPointReplaceField = value;
        }
    }
        
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Object is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='' attribute.
    public string AlignPoints {
        get {
            return _alignPointsField;
        }
        set {
            _alignPointsField = value;
        }
    }
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class AlignPointReplace {
}

/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
public partial class Version {
}
    
/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace=NKFontSchema.SCHEMA_NAMESPACE)]
[XmlRoot(Namespace=NKFontSchema.SCHEMA_NAMESPACE, IsNullable=false)]
public partial class FontMap {
        
    private object[] _itemsField;
        
    /// <remarks/>
    [XmlElement("AutoCompound", typeof(XmlAutoCompoundGlyphInfo))]
    [XmlElement("Component", typeof(XmlComponentGlyphInfo))]
    [XmlElement("Compound", typeof(XmlCompoundGlyphInfo))]
    [XmlElement("Ligature", typeof(XmlLigatureGlyphInfo))]
    public object[] Items {
        get {
            return _itemsField;
        }
        set {
            _itemsField = value;
        }
    }
}