// NeoKolors
// Copyright (c) 2025 KryKom

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NeoKolors.Tui.Generators;

[Generator]
public class StyleCollectionExtensionsGenerator : IIncrementalGenerator {
    
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        
        var properties = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is StructDeclarationSyntax or ClassDeclarationSyntax,
                static (ctx, _) => {
                    var decl = (TypeDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;

                    if (semanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol) return null;

                    var styleInterface = ctx.SemanticModel.Compilation.GetTypeByMetadataName("NeoKolors.Tui.Styles.Properties.IStyleProperty`2");
                    if (styleInterface == null) return null;

                    var implementation = symbol.AllInterfaces.FirstOrDefault(i => 
                        SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, styleInterface));

                    if (implementation == null) return null;

                    // IStyleProperty<TValue, TSelf>
                    var valueType = implementation.TypeArguments[0];
                    
                    return new StylePropertyInfo(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString(),
                        valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        symbol.DeclaredAccessibility
                    );
                }
            )
            .Where(static info => info is not null)
            .Select((info, _) => info!)
            .Collect();
        
        context.RegisterSourceOutput(properties, Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<StylePropertyInfo> properties) {
        var sb = new StringBuilder();

        sb.AppendLine(
            """
            // <auto-generated/>
            
            using NeoKolors.Tui.Styles.Properties;
            using NeoKolors.Tui.Styles.Values;
            
            namespace NeoKolors.Tui.Styles {
            
                public static partial class StyleCollectionExtensions {
            """
        );
        
        foreach (var prop in properties) {
            var name = prop.Name.EndsWith("Property") ? prop.Name.Substring(0, prop.Name.Length - 8) : prop.Name;
            var propType = $"global::{prop.Namespace}.{prop.Name}";
            var am = prop.GetAccess();
            
            sb.AppendLine(
                $"""
                
                        {am} static {prop.ValueType} Get{name}(this StyleCollection collection) => collection.Get<{propType}>().Value;
                        {am} static void Set{name}(this StyleCollection collection, {prop.ValueType} value) => collection.Set(new {propType}(value));
                        {am} static void Set{name}(this StyleCollection collection, {propType} value) => collection.Set(value);
                """
            );
        }

        sb.AppendLine(
            """
            #if NET_10_OR_GREATER
            
                    extension(StyleCollection collection) {
            """
        );
        
        foreach (var prop in properties) {
            var name = prop.Name.EndsWith("Property") ? prop.Name.Substring(0, prop.Name.Length - 8) : prop.Name;
            var propType = $"global::{prop.Namespace}.{prop.Name}";
            var am = prop.GetAccess();

            sb.AppendLine(
                $$"""
                
                            {{am}} {{prop.ValueType}} {{name}} {
                                get => collection.Get<{{propType}}>().Value;
                                set => collection.Set(new {{propType}}(value));
                            }
                """
            );
        }

        sb.AppendLine(
            """
                    }
            
            #endif
            
                }
            }
            """
        );
        
        context.AddSource("StyleCollectionExtensions.g.cs", sb.ToString());
    }
}

internal record StylePropertyInfo(string Name, string Namespace, string ValueType, Accessibility Accessibility) {
    public string Name { get; } = Name;
    public string Namespace { get; } = Namespace;
    public string ValueType { get; } = ValueType;
    public Accessibility Accessibility { get; } = Accessibility;

    public string GetAccess() {
        return Accessibility switch {
            Accessibility.NotApplicable => "",
            Accessibility.Private => "private",
            Accessibility.ProtectedAndInternal => "protected internal",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.Public => "public",
            _ => ""
        };
    }
}