//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using NeoKolors.Tui.Fonts.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = NKFontSchema.SCHEMA_NAMESPACE)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = NKFontSchema.SCHEMA_NAMESPACE, IsNullable=false)]
public partial class FontManifest {
    
    private string configField;
    
    private string mapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    public string Config {
        get {
            return this.configField;
        }
        set {
            this.configField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    public string Map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
}
