<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>2026.3</Version>
        <Authors>KryKom</Authors>
        <Company>KryKom</Company>
        <LangVersion>14</LangVersion>
        <TargetFrameworks>net10.0;net5.0;net8.0;netstandard2.1</TargetFrameworks>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <PackageProjectUrl>https://github.com/KryKomDev/NeoKolors</PackageProjectUrl>
        <PackageLicense>https://github.com/KryKomDev/NeoKolors/blob/main/LICENSE</PackageLicense>
        <RepositoryUrl>https://github.com/KryKomDev/NeoKolors</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>Package-Icon.png</PackageIcon>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <Description>the common utilities for the NeoKolors library pack</Description>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>

        <!--        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>-->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HasFlagExtension.Generator" Version="2026.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Implyzer" Version="2026.4.4" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="MessagePack" Version="3.1.8"/>
        <PackageReference Include="OneOf" Version="3.0.271"/>

        <PackageReference Include="SkiaSharp" Version="4.151.1"/>
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1"/>
        <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="4.151.1"/>
        <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1"/>
        <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="4.151.1"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <None Include="../../LICENSE" Pack="true" PackagePath="\"/>
        <None Include="../../Assets/Package-Icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Extensions/NeoKolors.Extensions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Docs\"/>
    </ItemGroup>
</Project>
