name: Build Template

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      project_path:
        required: true
        type: string
      test_project_path:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        cache: false

    - name: Restore Projects
      run: dotnet restore ${{ inputs.project_path }}

    - name: Build Projects
      run: dotnet build ${{ inputs.project_path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Restore Test Project 
      run: dotnet restore ${{ inputs.test_project_path }}

    - name: Build Test Project
      run: dotnet build ${{ inputs.test_project_path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test ${{ inputs.test_project_path }} --configuration ${{ matrix.configuration }} --no-build
