name: Build NeoKolors.Common

on:
  push:
    paths:
      - 'Src/Common/**'
      - 'Src/Tests/Common.Tests/**'
      - '.github/workflows/build-common.yml'
      - '.github/workflows/_build_template.yml'

jobs:
  build:
    uses: ./.github/workflows/_build_template.yml
    with:
      project_name: Common
      project_path: Src/Common/NeoKolors.Common.csproj
      test_project_path: Tests/Common.Tests/NeoKolors.Common.Tests.csproj
