name: Build NeoKolors.Extensions

on:
  push:
    paths:
      - 'Src/Extensions/**'
      - 'Src/Tests/Extensions.Tests/**'
      - '.github/workflows/build-extensions.yml'
      - '.github/workflows/_build_template.yml'

jobs:
  build:
    uses: ./.github/workflows/_build_template.yml
    with:
      project_name: Extensions
      project_path: Src/Extensions/NeoKolors.Extensions.csproj
      test_project_path: Tests/Extensions.Tests/NeoKolors.Extensions.Tests.csproj
