name: Build NeoKolors.Tui

on:
  push:
    paths:
      - 'Src/Tui/**'
      - 'Src/Tui.Generators/**'
      - 'Src/Tests/Tui.Tests/**'
      - '.github/workflows/build-tui.yml'
      - '.github/workflows/_build_template.yml'

jobs:
  build:
    uses: ./.github/workflows/_build_template.yml
    with:
      project_name: Tui
      project_path: Src/Tui/NeoKolors.Tui.csproj
      test_project_path: Tests/Tui.Tests/NeoKolors.Tui.Tests.csproj
