name: Build NeoKolors.Console

on:
  push:
    paths:
      - 'NeoKolors.Console/**'
      - 'NeoKolors.Console.Tests/**'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest 

    env:
      Solution_Name: NeoKolors.sln
      Test_Project_Path: NeoKolors.Console.Tests\NeoKolors.Console.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
