name: Build NeoKolors.Console

on:
  push:
    paths:
      - 'Src/Console/**'
      - 'Src/Tests/Console.Tests/**'
      - '.github/workflows/build-console.yml'
      - '.github/workflows/_build_template.yml'

jobs:
  build:
    uses: ./.github/workflows/_build_template.yml
    with:
      project_name: Console
      project_path: Src/Console/NeoKolors.Console.csproj
      test_project_path: Src/Tests/Console.Tests/NeoKolors.Console.Tests.csproj
