name: Build NeoKolors.Settings

on:
  push:
    paths:
      - 'Src/Settings/**'
      - 'Src/Tests/Settings.Tests/**'
      - '.github/workflows/build-settings.yml'
      - '.github/workflows/_build_template.yml'

jobs:
  build:
    uses: ./.github/workflows/_build_template.yml
    with:
      project_name: Settings
      project_path: Src/Settings/NeoKolors.Settings.csproj
      test_project_path: Src/Tests/Settings.Tests/NeoKolors.Settings.Tests.csproj
