name: Publish NeoKolors.Settings to NuGet

on:   
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_publish_template.yml
    with:
      project_name: Settings
      project_path: Src/Settings/NeoKolors.Settings.csproj
      test_project_path: Tests/Settings.Tests/NeoKolors.Settings.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
