name: Publish NeoKolors.Common to NuGet

on: 
  workflow_call:

permissions:
  packages: write

jobs: 
  build-and-publish:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Or your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/KryKomDev/index.json
