name: Publish NeoKolors.Extensions to NuGet

on:   
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_publish_template.yml
    with:
      project_name: Extensions
      project_path: Src/Extensions/NeoKolors.Extensions.csproj
      test_project_path: Src/Tests/Extensions.Tests/NeoKolors.Extensions.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
