name: Publish NeoKolors.Console to NuGet

on:   
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_publish_template.yml
    with:
      project_name: Console
      project_path: Src/Console/NeoKolors.Console.csproj
      test_project_path: Tests/Console.Tests/NeoKolors.Console.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
