name: Publish NeoKolors.Common to NuGet

on:   
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_publish_template.yml
    with:
      project_name: Common
      project_path: Src/Common/NeoKolors.Common.csproj
      test_project_path: Tests/Common.Tests/NeoKolors.Common.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
